"""Type stubs for google.cloud.datastore.batch"""

from typing import Any, List, Optional

from google.cloud.datastore.entity import Entity
from google.cloud.datastore.key import Key
from google.api_core import retry as retry_module
from google.cloud.datastore_v1.types import datastore as _datastore_pb2
from google.cloud.datastore_v1.types import entity as entity_pb2

class Batch:
    """An abstraction representing a collected group of updates / deletes."""

    _INITIAL: int
    _IN_PROGRESS: int
    _ABORTED: int
    _FINISHED: int

    _id: Optional[bytes]
    _client: Any
    _mutations: List[_datastore_pb2.Mutation]
    _partial_key_entities: List[Entity]
    _status: int

    def __init__(self, client: Any) -> None: ...

    def current(self) -> Optional[Batch]: ...

    @property
    def project(self) -> str: ...

    @property
    def database(self) -> Optional[str]: ...

    @property
    def namespace(self) -> Optional[str]: ...

    def _add_partial_key_entity_pb(self) -> entity_pb2.Entity: ...
    def _add_complete_key_entity_pb(self) -> entity_pb2.Entity: ...
    def _add_delete_key_pb(self) -> entity_pb2.Key: ...

    @property
    def mutations(self) -> List[_datastore_pb2.Mutation]: ...

    def _allow_mutations(self) -> bool: ...

    def put(self, entity: Entity) -> None: ...
    def delete(self, key: Key) -> None: ...
    def begin(self) -> None: ...
    def _commit(self, retry: Optional[retry_module.Retry], timeout: Optional[float]) -> None: ...
    def commit(self, retry: Optional[retry_module.Retry] = ..., timeout: Optional[float] = ...) -> None: ...
    def rollback(self) -> None: ...

    def __enter__(self) -> Batch: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

def _assign_entity_to_pb(entity_pb: entity_pb2.Entity, entity: Entity) -> None: ...
def _parse_commit_response(commit_response: Any) -> tuple[int, List[entity_pb2.Key]]: ...
