"""Type stubs for google.cloud.datastore.helpers"""

from typing import Any, Dict, List, Optional, Tuple, Union
import datetime

from google.cloud.datastore.entity import Entity
from google.cloud.datastore.key import Key
from google.cloud.datastore_v1.types import datastore as datastore_pb2
from google.cloud.datastore_v1.types import entity as entity_pb2
from google.cloud.datastore_v1.types import TransactionOptions
from google.type import latlng_pb2

class GeoPoint:
    """Simple container for a geo point value."""

    latitude: float
    longitude: float

    def __init__(self, latitude: float, longitude: float) -> None: ...
    def to_protobuf(self) -> latlng_pb2.LatLng: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

def entity_from_protobuf(pb: entity_pb2.Entity) -> Entity: ...
def entity_to_protobuf(entity: Entity) -> entity_pb2.Entity: ...
def key_from_protobuf(pb: entity_pb2.Key) -> Key: ...

def get_read_options(
    eventual: bool,
    transaction_id: Optional[bytes],
    read_time: Optional[datetime.datetime] = ...,
    new_transaction_options: Optional[TransactionOptions] = ...
) -> datastore_pb2.ReadOptions: ...

def get_transaction_options(
    transaction: Any
) -> Tuple[Optional[bytes], Optional[TransactionOptions]]: ...

def set_database_id_to_request(
    request: Dict[str, Any],
    database_id: Optional[str] = ...
) -> None: ...

def _get_meaning(value_pb: Any, is_list: bool = ...) -> Optional[Any]: ...
def _new_value_pb(entity_pb: entity_pb2.Entity, name: str) -> entity_pb2.Value: ...
def _set_pb_meaning_from_entity(
    entity: Entity,
    name: str,
    value: Any,
    value_pb: entity_pb2.Value,
    is_list: bool = ...
) -> None: ...
def _pb_attr_value(val: Any) -> Tuple[str, Any]: ...
def _get_value_from_value_pb(pb: Any) -> Any: ...
def _set_protobuf_value(value_pb: entity_pb2.Value, val: Any) -> None: ...
