"""Type stubs for google.cloud.ndb._datastore_query"""

from typing import Any, Iterator

class Cursor:
    """A query cursor for pagination."""
    def __init__(self, cursor: bytes = ...) -> None: ...
    def to_bytes(self) -> bytes: ...
    def urlsafe(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, urlsafe: bytes) -> Cursor: ...

class QueryIterator(Iterator[Any]):
    """Iterator for query results."""
    def __init__(self, query: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> QueryIterator: ...
    def __next__(self) -> Any: ...
