"""Type stubs for google.cloud.ndb.context"""

from typing import Any, Callable, Dict, Iterable, List, Optional, Type, TypeVar, Union

from google.cloud.ndb import key as key_module
from google.cloud.ndb import tasklets

_T = TypeVar("_T")
_ModelT = TypeVar("_ModelT", bound="model.Model")

class ContextOptions:
    """Options for Context operations."""

    def __init__(
        self,
        *,
        deadline: Optional[float] = ...,
        use_cache: Optional[bool] = ...,
        use_global_cache: Optional[bool] = ...,
        global_cache_timeout: Optional[int] = ...,
        use_datastore: Optional[bool] = ...,
        use_memcache: Optional[bool] = ...,
        memcache_timeout: Optional[int] = ...,
        max_memcache_items: Optional[int] = ...,
        force_writes: Optional[bool] = ...,
        retries: Optional[int] = ...,
        timeout: Optional[float] = ...,
        read_consistency: Optional[Any] = ...,
        read_policy: Optional[Any] = ...,
        transaction: Optional[bytes] = ...,
        xg: Optional[bool] = ...,
        propagation: Optional[Any] = ...,
        retry_on: Optional[Callable[[Exception], bool]] = ...,
    ) -> None: ...

class TransactionOptions:
    """Options for transactions."""

    def __init__(
        self,
        *,
        mode: Optional[Any] = ...,
        xg: bool = ...,
        propagation: Optional[Any] = ...,
        retries: int = ...,
    ) -> None: ...

class AutoBatcher:
    """Batches datastore operations automatically."""
    ...

class Context:
    """Runtime context for NDB operations."""

    def __init__(
        self,
        client: Any,
        *,
        namespace: Optional[str] = ...,
        eventloop: Optional[Any] = ...,
        batches: Optional[Any] = ...,
        commit_batches: Optional[Any] = ...,
        cache: Optional[Dict[Any, Any]] = ...,
        cache_policy: Optional[Callable[[key_module.Key], bool]] = ...,
        global_cache: Optional[Any] = ...,
        global_cache_policy: Optional[Callable[[key_module.Key], bool]] = ...,
        global_cache_timeout_policy: Optional[Callable[[key_module.Key], int]] = ...,
        datastore_policy: Optional[Callable[[key_module.Key], bool]] = ...,
        on_commit_callbacks: Optional[List[Callable[[], None]]] = ...,
        transaction: Optional[bytes] = ...,
        legacy_data: bool = ...,
    ) -> None: ...

    def use(self) -> Context: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

    def clear_cache(self) -> None: ...
    def flush(self) -> None: ...
    def get_namespace(self) -> Optional[str]: ...
    def get_cache_policy(self) -> Optional[Callable[[key_module.Key], bool]]: ...
    def get_datastore_policy(self) -> Optional[Callable[[key_module.Key], bool]]: ...
    def get_global_cache_policy(self) -> Optional[Callable[[key_module.Key], bool]]: ...
    def get_global_cache_timeout_policy(self) -> Optional[Callable[[key_module.Key], int]]: ...

    def set_cache_policy(self, policy: Optional[Callable[[key_module.Key], bool]]) -> None: ...
    def set_datastore_policy(self, policy: Optional[Callable[[key_module.Key], bool]]) -> None: ...
    def set_global_cache_policy(self, policy: Optional[Callable[[key_module.Key], bool]]) -> None: ...
    def set_global_cache_timeout_policy(self, policy: Optional[Callable[[key_module.Key], int]]) -> None: ...

    def call_on_commit(self, callback: Callable[[], None]) -> None: ...
    def in_transaction(self) -> bool: ...
    def in_retry(self) -> bool: ...

    def memcache_add(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_cas(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_decr(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_delete(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_get(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_gets(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_incr(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_replace(self, *args: Any, **kwargs: Any) -> Any: ...
    def memcache_set(self, *args: Any, **kwargs: Any) -> Any: ...

    def urlfetch(self, *args: Any, **kwargs: Any) -> Any: ...

def get_context(raise_context_error: bool = ...) -> Context: ...
def get_toplevel_context(raise_context_error: bool = ...) -> Context: ...
