"""Type stubs for google.cloud.ndb.key"""

from typing import Any, Dict, Iterable, List, Optional, Tuple, Union, overload

UNDEFINED: object

class Key:
    """An immutable datastore key."""

    def __init__(
        self,
        *args: Union[str, int, type],
        pairs: Optional[List[Tuple[str, Union[str, int, None]]]] = ...,
        flat: Optional[List[Union[str, int]]] = ...,
        parent: Optional[Key] = ...,
        namespace: Optional[str] = ...,
        app: Optional[str] = ...,
        project: Optional[str] = ...,
        database: Optional[str] = ...,
        urlsafe: Optional[Union[str, bytes]] = ...,
        reference: Optional[Any] = ...,
        serialized: Optional[bytes] = ...,
    ) -> None: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: Key) -> bool: ...
    def __le__(self, other: Key) -> bool: ...
    def __gt__(self, other: Key) -> bool: ...
    def __ge__(self, other: Key) -> bool: ...

    @overload
    def __getstate__(self) -> Tuple[bytes]: ...
    @overload
    def __setstate__(self, state: Tuple[bytes]) -> None: ...

    def app(self) -> str: ...
    def pairs(self) -> Tuple[Tuple[str, Union[str, int, None]], ...]: ...
    def flat(self) -> Tuple[Union[str, int, None], ...]: ...

    @property
    def kind(self) -> str: ...

    def string_id(self) -> Optional[str]: ...
    def id(self) -> Optional[Union[str, int]]: ...
    def integer_id(self) -> Optional[int]: ...
    def namespace(self) -> Optional[str]: ...
    def project(self) -> str: ...
    def database(self) -> Optional[str]: ...
    def parent(self) -> Optional[Key]: ...
    def root(self) -> Key: ...

    def urlsafe(self) -> bytes: ...
    def serialized(self) -> bytes: ...
    def reference(self) -> Any: ...
    def to_legacy_urlsafe(self, location_prefix: Optional[str] = ...) -> bytes: ...

    @classmethod
    def from_legacy_urlsafe(cls, urlsafe: Union[bytes, str]) -> Key: ...

    def get(self, **ctx_options: Any) -> Optional[Any]: ...
    def get_async(self, **ctx_options: Any) -> Any: ...  # Returns Future
    def delete(self, **ctx_options: Any) -> None: ...
    def delete_async(self, **ctx_options: Any) -> Any: ...  # Returns Future
