"""Type stubs for google.cloud.ndb.tasklets"""

from typing import Any, Callable, Coroutine, Generator, Generic, Iterable, List, Optional, TypeVar, Union

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)

class Return(StopIteration, Generic[_T]):
    """Return value from a tasklet."""
    value: _T
    def __init__(self, value: _T) -> None: ...

class Future(Generic[_T]):
    """Represents an asynchronous computation."""

    def __init__(self) -> None: ...

    def set_result(self, result: _T) -> None: ...
    def set_exception(self, exception: BaseException) -> None: ...
    def done(self) -> bool: ...
    def running(self) -> bool: ...
    def wait(self) -> None: ...
    def check_success(self) -> None: ...
    def get_result(self) -> _T: ...
    def get_exception(self) -> Optional[BaseException] ...
    def get_traceback(self) -> Optional[Any]: ...
    def add_done_callback(self, callback: Callable[[Future[_T]], Any]) -> None: ...
    def remove_done_callback(self, callback: Callable[[Future[_T]], Any]) -> None: ...
    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def result(self) -> _T: ...
    def exception(self) -> Optional[BaseException]: ...
    def __iter__(self) -> Generator[Future[_T], None, _T]: ...
    def __await__(self) -> Generator[Future[_T], None, _T]: ...

class MultiFuture(Future[List[_T]]):
    """Future that waits for multiple futures."""
    def __init__(self, futures: Iterable[Future[_T]]) -> None: ...

class QueueFuture(Future[List[_T]]):
    """Future that processes items from a queue."""
    ...

class SerialQueueFuture(Future[List[_T]]):
    """Future that processes items from a queue serially."""
    ...

class ReducingFuture(Future[_T]):
    """Future that reduces results."""
    def __init__(
        self,
        reducer: Callable[[_T, _T], _T],
        futures: Iterable[Future[_T]],
        initial: Optional[_T] = ...
    ) -> None: ...

def tasklet(func: Callable[..., Generator[Any, Any, _T]]) -> Callable[..., Future[_T]]: ...
def synctasklet(func: Callable[..., Generator[Any, Any, _T]]) -> Callable[..., _T]: ...
def toplevel(func: Callable[..., Any]) -> Callable[..., None]: ...

def sleep(seconds: float) -> Future[None]: ...
def wait_all(futures: Iterable[Future[Any]]) -> None: ...
def wait_any(futures: Iterable[Future[Any]]) -> None: ...

def make_context(**kwargs: Any) -> Any: ...  # Returns Context
def make_default_context(**kwargs: Any) -> Any: ...  # Returns Context
def set_context(context: Any) -> None: ...
def add_flow_exception(exc: BaseException) -> None: ...
